# reproducibility
seed: 42

# training
device: cuda:1
batch_size: 256
num_epochs: 130
learning_rate: 0.001
num_workers: 0
dropout: 0.4

# data configs
dataset: IMUPoser
target_fps: 30
add_noise: true

# output directory
output_dir: checkpoints

# model config
past_frames: 40
future_frames: 5
total_frames: past_frames + future_frames

# settings
use_global_pose: true
normalize_imu: true
use_r6d_input: false
window_length: 150

# wandb
wandb_project: SimplePoser
wandb_run_name: rprw_30fps_normalized
wandb_group: rightpocket