# reproducibility
seed: 42

# training
device: cuda
batch_size: 256
num_epochs: 200
learning_rate: 0.001
num_workers: 0
dropout: 0.4

output_dir: checkpoints

# model config
target_fps: 60
past_frames: 40
future_frames: 5
total_frames: past_frames + future_frames

# settings
use_global_pose: true
window_length: 300

# wandb
wandb_project: SimplePoser
wandb_run_name: right_pocket
wandb_group: scratch