# reproducibility
seed: 42

# training
device: cuda:2
batch_size: 32
num_epochs: 15
learning_rate: 0.0001
num_workers: 0
dropout: 0.4

# data configs
dataset: IMUPoser
add_noise: false

# output directory
output_dir: checkpoints

# model config
target_fps: 30
past_frames: 40
future_frames: 5
use_r6d_input: false
total_frames: past_frames + future_frames
pretrained: checkpoints/rp_amass_30/best.pt

# settings
use_global_pose: true
window_length: 150

# wandb
wandb_project: SimplePoser
wandb_run_name: rp_amass_30
wandb_group: rightpocket
