# reproducibility
seed: 42

# training
device: cuda:0
batch_size: 64
num_epochs: 10
# learning_rate: 0.0003
learning_rate: 0.00001
num_workers: 0
dropout: 0.2

# data configs
dataset: Finetune
add_noise: false

# output directory
output_dir: checkpoints

# model config
target_fps: 30
past_frames: 40
future_frames: 5
use_r6d_input: false
total_frames: past_frames + future_frames
pretrained: checkpoints/dynaip_amass/finetune/best.pt

# settings
use_global_pose: true
window_length: 300

# wandb
wandb_project: SimplePoser
wandb_run_name: dynaip_amass
wandb_group: dynaip_amass
